### ISSUE TITLE
Os campos da sessão estão vindo vazios

### ISSUE THREAD

**Issue by GustavoDMS** [wppconnect-team/wppconnect-csharp#3]
Consegui rodar perfeito a lib aqui, porem quando vai gravar a sessão os campos vem nulos.
`{"WAToken1":null,"WAToken2":null,"WASecretBundle":"","WABrowserId":"\"Yi3s4ijJdXL13UKMbNohyQ==\""}`

**Comment by GustavoDMS** [comment]
Esqueci de mencionar, isso com o multi device habilitado.

**Comment by renerlemes** [comment]
Eu não cheguei a testar com multidevice, mas vou fazer alguns testes agora na parte da tarde e aviso por aqui

**Comment by edgardmessias** [comment]
Com o multidevice, sempre vão vir vazios, para manter autenticação no beta, precisa setar uma pasta para salvar o userDataDir

**Comment by renerlemes** [comment]
Eu achei aqui uma forma de fazer essa parte do useDataDir no Playwright. Vou fazer alguns testes e ver se funciona tudo e retornar aqui. Valeu @edgardmessias pela dica, já me ajudou em pesquisar pra saber o que precisaria fazer. Só uma dúvida, o WABrowserId não retorna null, eu preciso setar ela da mesma forma também pra manter logado?

**Comment by edgardmessias** [comment]
Não precisa setar, pois ao usar o userDataDir ele já vai carregar automaticamente

**Comment by GustavoDMS** [comment]
> Não precisa setar, pois ao usar o userDataDir ele já vai carregar automaticamente

Obrigado, consegui aqui!

**Comment by renerlemes** [comment]
Foi implementado o uso do useDataDir para armazenar as sessões tanto para single e multidevice
